name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  package:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: --target x86_64-pc-windows-msvc --bundles nsis,msi
            rust_targets: x86_64-pc-windows-msvc
          - platform: macos-14
            args: --target aarch64-apple-darwin --bundles dmg
            rust_targets: aarch64-apple-darwin
          - platform: macos-13
            args: --target x86_64-apple-darwin --bundles dmg
            rust_targets: x86_64-apple-darwin
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust_targets }}
      - run: pnpm install --frozen-lockfile
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
